version: '3.8'

services:
  backend:
    image: your-backend-image
    container_name: backend
    ports:
      - "5000:5000" # Assicurati che questa porta sia quella che il tuo backend utilizza
    environment:
      MONGODB_URI: mongodb://mongo:27017/ProgettoWeb # Configura l'URL di connessione per MongoDB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Porta di MongoDB, se devi accedere direttamente
    volumes:
      - mongo_data:/data/db # Persistenza dei dati

volumes:
  mongo_data:
